### ISSUE TITLE
Tag for 14.0.6 is Invalid

### ISSUE THREAD

**Issue by JoshuaFortriede** [aldefouw/redcap_rsvc#234]
The Tag for v14.0.6 is invalid. 

First, it does not contain a package.json file. Second, the tag utilizes a capital "V" instead of a lowercase "v". This is inconsistent with the other tags.

**Comment by aldefouw** [comment]
@JoshuaFortriede  - Thanks.  We chatted about this at REDCap Con and discovered this was a tag for manual that carried across the fork.  I deleted it on the remote and so therefore I'm closing.
